[package]
name = "resolvelib-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
petgraph = "0.6.3"
rustc-hash = "1.1.0"
thiserror = "1.0.40"
